# Generated by Django 5.2.6 on 2025-09-18 12:48

import events.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFTS', 'drafts'), ('ACTIVE', 'active'), ('ARCHIVED', 'archived'), ('DELETED', 'deleted')], default='DRAFTS', max_length=255)),
                ('category', models.CharField(choices=[('MUSIC', 'Music events'), ('ART', 'Art events'), ('MOVIES', 'Movie events'), ('COMEDY', 'Comedy events'), ('SPORTS', 'Sports events'), ('FASHION', 'Fashion events'), ('TECH', 'Tech events'), ('EDUCATION', 'Educational events'), ('BUSINESS', 'Business events'), ('OTHER', 'Other events')], max_length=255, null=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('default_image', models.ImageField(null=True, upload_to=events.models.get_default_image_upload_path)),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('NGN', 'Nigerian Naira'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling')], default='USD', max_length=10)),
                ('payment_plan', models.CharField(choices=[('FREE', 'Free event'), ('PAID', 'Paid event'), ('DONATION', 'Donation based event')], default='FREE', max_length=255)),
                ('ticket_link', models.URLField(blank=True, max_length=500, null=True)),
                ('total_tickets', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
