# Generated by Django 5.2.6 on 2025-09-18 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=256, null=True)),
                ('reference', models.CharField(max_length=256)),
                ('amount', models.PositiveBigIntegerField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('NGN', 'Nigerian Naira'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling')], default='NGN', max_length=10)),
                ('fee', models.PositiveBigIntegerField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('SUCCESS', 'Successful Payment'), ('FAILED', 'Failed Payment')], default='PENDING', max_length=256)),
                ('payment_method', models.CharField(choices=[('PAYSTACK', 'Paystack Payment Service')], default='PAYSTACK', max_length=256)),
                ('error_message_from_payment_service', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'db_table': 'transaction_logs',
            },
        ),
    ]
