# Generated by Django 5.2.6 on 2025-09-18 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='payed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_logs_consumer_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_logs_creator_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
