# Generated by Django 5.2.6 on 2025-09-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notifications_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='user_role',
            field=models.CharField(choices=[('CONSUMER', 'Consumer'), ('CREATOR', 'Creator')], default='CONSUMER', max_length=256),
        ),
    ]
